# Generated by Django 3.2.6 on 2021-08-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210815_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down vVote')], max_length=200, null=True),
        ),
    ]
